name: restlib_docs
description: A sample command-line application
dependencies:
  restlib_common:
    git: https://code.google.com/p/dart-restlib.common/
  restlib_core:
    git: https://code.google.com/p/dart-restlib.core/
  restlib_http_connector:
    git: https://code.google.com/p/dart-restlib.http-connector/
  restlib_parsing:
    git: https://code.google.com/p/dart-restlib.parsing/
  restlib_server:
    git: https://code.google.com/p/dart-restlib.server/
  restlib_testing:
    git: https://code.google.com/p/dart-restlib.testing/
